strictness: veryhigh
test-warnings: true
doc-warnings: true
autodetect: false
max-line-length: 170
pep8:
    full: true
#  disable:
#      - N803 # argument name should be lowercase
#      - N806 # variable in function should be lowercase
#      - N812 # lowercase imported as non lowercase

pylint:
    run: true
    disable:
      - too-many-instance-attributes
      - too-many-locals
      - too-many-arguments
      - abstract-method
      - pointless-string-statement
      - no-self-use
      - too-many-statements
      - too-few-public-methods
      - unnecessary-pass
      - too-many-lines
      - too-many-public-methods
      - too-many-branches
#    disable:
#      - too-many-locals
#      - arguments-differ
#      - no-else-return
#      - inconsistent-return-statements

pep257:
    run: true
#    disable:
#      - D203 # 1 blank line required before class docstring
#      - D212 # Multi-line docstring summary should start at the first line
#      - D213 # Multi-line docstring summary should start at the second line

pycodestyle:
  disable:
    - N806
    - N803
    - N802
    - E128
    - E122

pydocstyle:
  run: true
  disable:
    - D401
    - D210
    - D202
    - D213
    - W293
    - D211


mypy:
  run: true

bandit:
  run: false
  options:
    config: .bandit.yml

#frosted:
#  run: true

pyroma:
  run: false

vulture:
  run: false
  disable:
    - unused-variable
    - unused-function
    - unused-attribute

mccabe:
  run: true
  disable:
    - MC0001

