"""Test for json config generation and execution."""
from pathlib import Path
import shutil
import pytest
from hisim import utils
from hisim.hisim_convert_to_json import write_json_for_initialized_simulator
import hisim.simulator as sim
from hisim.simulationparameters import SimulationParameters
from hisim.hisim_main import initialize_from_python, initialize_from_json
from tests.testing_utils import TestingUtils


# This system setup generation from directory was generated by ChatGPT
SYSTEM_SETUP_DIR: Path = Path("../system_setups")
SYSTEM_SETUPS: list[tuple[str]] = [
    (str(path),)
    for path in sorted(SYSTEM_SETUP_DIR.glob("*.py"))
    if path.name != "__init__.py"
]


@pytest.mark.jsonconfig
@pytest.mark.parametrize(["system_setup"], SYSTEM_SETUPS)
@utils.measure_execution_time
def test_json(system_setup: str) -> None:
    """Test generation and execution of JSON configs."""

    system_setup_path = Path(system_setup)
    output_directory = Path(TestingUtils.get_result_directory(test_name="test_json_configs")) / system_setup_path.stem
    shutil.rmtree(output_directory, ignore_errors=True)
    my_simulation_parameters = SimulationParameters.one_week_only(year=2021, seconds_per_timestep=60 * 60)
    my_simulation_parameters.log_connections = True
    my_simulation_parameters.result_directory = str(output_directory / "python")

    try:
        sim_py = initialize_from_python(
            path_to_module=system_setup,
            my_simulation_parameters=my_simulation_parameters,
        )
    except Exception:
        pytest.skip(f"Python configuration {system_setup} fails. Skipping JSON test for this configuration.")
    else:
        scenario_path, simulation_parameters_path = write_json_for_initialized_simulator(
            path_to_module=system_setup,
            my_sim=sim_py,
            output_directory=str(output_directory),
        )
        sim_json = initialize_from_json(
            scenario=str(scenario_path),
            simulation_parameters=str(simulation_parameters_path),
            path_to_module=str(scenario_path),
            delta=None,
        )
        sim_json.prepare_calculation()
        sim_json.connect_all_components()

        num_components_py, num_outputs_py = get_num_of_components_and_outputs(sim_py)
        num_components_json, num_outputs_json = get_num_of_components_and_outputs(sim_json)

        assert num_components_py == num_components_json
        assert num_outputs_py == num_outputs_json


def get_num_of_components_and_outputs(simulator: sim.Simulator) -> tuple[int, int]:
    """Helper function to get the number of components and outputs in the current simulator."""

    num_components = len(simulator.wrapped_components)
    num_outputs = len(simulator.all_outputs)
    return num_components, num_outputs
