"""The committed translation map is the page this translator renders today.

Decision V1 asked for a page a reviewer can open instead of reading the code. Two things are
tested. The **freshness claim**: ``roadmap/renovisor/translation_map.html`` is regenerated by
``python -m hisim.renovisor map``, and a change to the translator that nobody regenerated the
page for is a failing test rather than a stale picture. And the **content**: the page shows
every catalogue measure, every inventory field the probes reached, and the review's D-E
distinction between a substitution and a gap.
"""

import re
from pathlib import Path

import pytest

from hisim.renovisor.map import MapPalette, TranslationMap
from hisim.renovisor.request import CatalogueTable


@pytest.fixture(scope="module")
def page() -> str:
    """Render the page once; every test in this module reads the same render."""
    return TranslationMap.render()


@pytest.mark.base
class TestTheCommittedPageIsCurrent:
    """The freshness claim of decision V1."""

    def test_the_committed_file_is_what_the_generator_produces(self, page: str) -> None:
        """Regenerate it with ``python -m hisim.renovisor map`` when this fails."""
        committed = TranslationMap.PATH.read_text(encoding="utf-8")

        assert committed == page, (
            "roadmap/renovisor/translation_map.html is out of date; "
            "run `python -m hisim.renovisor map` and commit the result"
        )

    def test_rendering_twice_produces_the_same_page(self, page: str) -> None:
        """Nothing on it carries a clock, which is what makes the freshness test possible."""
        assert TranslationMap.render() == page

    def test_writing_it_somewhere_else_leaves_the_committed_one_alone(self, tmp_path: Path) -> None:
        """So that a reviewer can render it without dirtying the repository."""
        before = TranslationMap.PATH.read_text(encoding="utf-8")
        target = tmp_path / "map.html"

        assert TranslationMap.write(target) == 0

        assert target.read_text(encoding="utf-8") == before


@pytest.mark.base
class TestWhatThePageShows:
    """One row per measure, one per inventory field, and the two kinds of omission apart."""

    def test_it_is_one_self_contained_html_file(self, page: str) -> None:
        """It travels as an attachment to a contract discussion and opens from a file system."""
        assert page.startswith("<!doctype html>")
        assert "<script src=" not in page
        assert "<link rel=" not in page

    def test_every_catalogue_measure_has_a_row(self, page: str) -> None:
        """A measure that fell out of the registry would fall off the page with it."""
        for measure_id in CatalogueTable.ids():
            assert f"<code>{measure_id}</code>" in page

    def test_the_header_counts_the_measures_by_status(self, page: str) -> None:
        """The tally the acceptance criterion names, printed where a reader sees it first."""
        assert re.search(r"measures: \d+ supported, \d+ approximated, \d+ not_implemented_yet", page)

    def test_the_legend_tells_a_substitution_apart_from_a_gap(self, page: str) -> None:
        """The review's D-E: the frontend hides one class and may offer the other."""
        assert "substituted" in page
        assert MapPalette.BY_STATUS["substituted"][2] in page
        assert MapPalette.BY_STATUS["not_implemented_yet"][2] in page

    def test_a_measure_with_no_model_is_marked_as_a_gap(self, page: str) -> None:
        """``outside_shading`` has no Building parameter at all, so it is not a substitution."""
        row = page[page.index("<code>outside_shading</code>"):][:400]
        assert "not_implemented_yet" in row

    def test_the_worked_example_traces_the_vendored_mockup(self, page: str) -> None:
        """One example, and the page shows all four of its stages."""
        assert "The request (the vendored mockup)" in page
        assert "The house after the package" in page
        assert "The mapping report" in page
        assert "renovisor_" in page

    def test_the_inventory_table_names_request_paths(self, page: str) -> None:
        """A reader looking for one field looks for its own path, not for a HiSim name."""
        assert "house.building.facade.u_value_in_watt_per_m2_per_kelvin" in page
        assert "house.occupancy.number_of_residents" in page
