"""The translation map: the whole translation layer as one committed HTML page.

Decision V1 asked for a page a reviewer can open instead of reading the code: every catalogue
measure and every inventory field with what the translator does to it, the status colour that
says how well, and one worked example traced from a request through to the file that would run.
It is generated by the same probe run the capability document is aggregated from, so the page
cannot claim a capability the translator does not have::

    python -m hisim.renovisor map

One file, inline CSS and no libraries, because it travels as an attachment to a contract
discussion and has to open from a file system. ``tests/test_renovisor_map.py`` asserts that the
committed page is the one this module renders today, so a change to the translator that nobody
regenerated the page for is a failing test rather than a stale picture.

The review's D-E asked for one distinction the earlier page did not draw: a ``not_implemented_yet``
item whose note says it is *modelled as* something else is a **substitution**, and one that has
no model at all is a **gap**. The frontend hides the first class and may offer the second with
its note, so the page marks them differently and the capability document carries the same
``substitution`` flag.

The page carries one more table than the capability document's measure and field sections: the
**result payload**, which is the document's own ``results`` section printed -- every field
``result.json`` can carry, where its number comes from and whether it will be a simulation
result, a constant, a partly-estimated figure or nothing at all.
"""

import html
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, ClassVar, Dict, List, Mapping, Optional, Sequence, Tuple

from hisim.renovisor import TRANSLATOR_VERSION
from hisim.renovisor.apply import apply
from hisim.renovisor.capabilities import CapabilityDocument
from hisim.renovisor.contract import ContractFiles
from hisim.renovisor.request import Request
from hisim.renovisor.translate import Translator
from hisim.renovisor.whitelist import Whitelist


class MapPalette:
    """The colour of each status on the page, and what the legend calls it.

    Four statuses and one extra distinction: a ``not_implemented_yet`` item that is modelled as
    something else is amber (a substitution the user still gets a simulation for) and one with
    no model at all is red (a gap). Colours are chosen to stay apart in greyscale, because the
    page is printed as often as it is opened.
    """

    #: status key -> (background, foreground, the legend's word).
    BY_STATUS: ClassVar[Dict[str, Tuple[str, str, str]]] = {
        "supported": ("#d8efd8", "#14501a", "mapped and written"),
        "used": ("#d8efd8", "#14501a", "mapped and written"),
        "approximated": ("#fdf0cf", "#6b4a06", "modelled by something close"),
        "defaulted": ("#e3ecf7", "#173a63", "absent, filled in by the translator"),
        "substituted": ("#fbe3cd", "#7a3a09", "not implemented, modelled as something else"),
        "not_implemented_yet": ("#fadcdc", "#7a1616", "not implemented, no model"),
    }

    @classmethod
    def key_for(cls, status: str, substitution: bool) -> str:
        """Return the palette key of one status, splitting the two kinds of omission."""
        if status == "not_implemented_yet" and substitution:
            return "substituted"
        return status

    @classmethod
    def style(cls, key: str) -> str:
        """Return the inline style of one palette key."""
        background, foreground, _ = cls.BY_STATUS.get(key, ("#eee", "#333", ""))
        return f"background:{background};color:{foreground}"


class ResultsPane:
    """How the capability document's ``results`` section is read onto the page.

    The section is data -- ``{"kpis": [...], "costs": [...]}``, each entry a field of
    ``result.json`` with its provenance -- and this is the one place that says how it is
    coloured and how an entry's conditions, reason and circumstance become the one cell a reader
    sees. Nothing here recomputes anything: the page prints what the document already says.
    """

    #: The key the KPI half of the section sits under; the payload block's own name.
    KPIS_KEY: ClassVar[str] = "kpis"

    #: The key the cost half sits under.
    COSTS_KEY: ClassVar[str] = "costs"

    #: Which palette key each provenance borrows its colour from. A simulated figure is green
    #: like a mapped field, a partly-estimated one amber like an approximation, a constant blue
    #: like a defaulted value and an absent field red like a gap, so one legend serves the page.
    PALETTE_KEYS: ClassVar[Dict[str, str]] = {
        "SIMULATED": "supported",
        "PARTIAL": "approximated",
        "MOCKED": "defaulted",
        "absent": "not_implemented_yet",
    }

    @classmethod
    def conditions(cls, entry: Mapping[str, Any]) -> str:
        """Return the conditions cell of one result row.

        Args:
            entry: One entry of the document's ``results`` section.

        Returns:
            A list item per condition, then the circumstance the field is absent under and the
            sentence the payload's ``missing`` entry carries, or a middle dot when the field has
            none of them.
        """
        items = [str(condition) for condition in entry.get("conditions") or ()]
        if entry.get("when"):
            items.append(str(entry["when"]))
        if entry.get("reason"):
            items.append(f"missing: {entry['reason']}")
        if not items:
            return "&middot;"
        rendered = "".join(f"<li>{html.escape(item)}</li>" for item in items)
        return f"<ul>{rendered}</ul>"


@dataclass(frozen=True)
class TraceExample:
    """The worked example the page traces, end to end.

    Args:
        request: The request as it arrived.
        renovated: The house after the package.
        yaml_text: The energy-system file the translator produced.
        report: The mapping report.
        base_file: The twin the file came from.
    """

    request: Mapping[str, Any]
    renovated: Mapping[str, Any]
    yaml_text: str
    report: Mapping[str, Any]
    base_file: str

    @classmethod
    def build(cls, base_files_directory: Optional[Path] = None) -> "TraceExample":
        """Trace the vendored mockup: the one example both sides of the contract point at."""
        directory = base_files_directory or (Path(__file__).resolve().parents[2] / "energy_systems")
        whitelist = Whitelist.load()
        request = Request.parse(ContractFiles.request_mockup())
        applied = apply(request.document["house"], request.measures, whitelist)
        translated = Translator(directory, whitelist).translate(request, applied)
        return cls(
            request=request.document,
            renovated=applied.house,
            yaml_text=translated.yaml_text,
            report=translated.report.to_json(),
            base_file=translated.base_file_name,
        )


class TranslationMap:
    """Renders the page and writes it where the test expects to find it."""

    #: Where the committed page lives, relative to the repository root.
    PATH: ClassVar[Path] = (
        Path(__file__).resolve().parents[2] / "roadmap" / "renovisor" / "translation_map.html"
    )

    #: The page's title, in the tab and in the heading.
    TITLE: ClassVar[str] = "RenoVisor translation map"

    #: The timestamp the page carries. It is the translator version and the catalogue revision,
    #: never a clock: a page that changed because it was regenerated on a Tuesday would fail its
    #: own freshness test every Tuesday.
    GENERATED_AT: ClassVar[str] = "fixed by content, not by the clock"

    @classmethod
    def render(cls, base_files_directory: Optional[Path] = None) -> str:
        """Return the whole page as one string.

        Args:
            base_files_directory: Where the recorded twins live.

        Returns:
            The HTML, deterministic for one state of the translator.
        """
        document = CapabilityDocument.build(
            generated_at=cls.GENERATED_AT, base_files_directory=base_files_directory
        )
        trace = TraceExample.build(base_files_directory)
        parts: List[str] = [
            "<!doctype html>",
            '<html lang="en"><head><meta charset="utf-8">',
            f"<title>{html.escape(cls.TITLE)}</title>",
            f"<style>{cls._style()}</style></head><body>",
            f"<h1>{html.escape(cls.TITLE)}</h1>",
            cls._header(document),
            cls._legend(),
            cls._measures(document.body["measures"]),
            cls._fields(document.body["fields"]),
            cls._results(document.body["results"]),
            cls._trace(trace),
            "</body></html>",
            "",
        ]
        return "\n".join(parts)

    @classmethod
    def write(cls, path: Optional[Path] = None) -> int:
        """Render the page and write it.

        Args:
            path: Where to write it; the committed location when omitted.

        Returns:
            ``0``, which the command line returns as its exit code.
        """
        target = path or cls.PATH
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(cls.render(), encoding="utf-8")
        return 0

    @classmethod
    def _style(cls) -> str:
        """Return the page's stylesheet, inline and small."""
        return (
            "body{font:14px/1.5 system-ui,sans-serif;margin:0;padding:24px;background:#fafafa;"
            "color:#1a1a1a;max-width:1180px}"
            "h1{font-size:22px;margin:0 0 4px}h2{font-size:17px;margin:28px 0 8px}"
            "table{border-collapse:collapse;width:100%;background:#fff;font-size:13px}"
            "th,td{border:1px solid #dcdcdc;padding:5px 8px;text-align:left;vertical-align:top}"
            "th{background:#f0f0f0;font-weight:600}"
            "code{font:12px ui-monospace,monospace;background:#f4f4f4;padding:0 3px}"
            "pre{background:#fff;border:1px solid #dcdcdc;padding:10px;overflow:auto;font-size:12px;"
            "max-height:420px}"
            ".s{display:inline-block;padding:1px 7px;border-radius:9px;font-size:11px;font-weight:600;"
            "white-space:nowrap}"
            ".meta{color:#555;font-size:12px;margin:0 0 12px}"
            ".legend span{margin-right:14px}"
            "ul{margin:4px 0 0;padding-left:18px}"
        )

    @classmethod
    def _header(cls, document: CapabilityDocument) -> str:
        """Return the provenance line: which translator, which catalogue, how many probes."""
        tally = document.tally()
        translator = document.body["translator"]
        counted = ", ".join(f"{count} {name}" for name, count in tally.items())
        return (
            f'<p class="meta">translator {html.escape(TRANSLATOR_VERSION)} &middot; catalogue '
            f'{html.escape(str(translator["catalogue_revision"]))} &middot; '
            f'{translator["probes"]} probes &middot; measures: {html.escape(counted)}</p>'
        )

    @classmethod
    def _legend(cls) -> str:
        """Return the colour legend, which is the page's own vocabulary."""
        items = "".join(
            f'<span><span class="s" style="{cls.style_of(key)}">{html.escape(key)}</span> '
            f"{html.escape(word)}</span>"
            for key, (_, _, word) in MapPalette.BY_STATUS.items()
            if key != "used"
        )
        return f'<p class="legend">{items}</p>'

    @classmethod
    def style_of(cls, key: str) -> str:
        """Return the inline style of one palette key, for a badge."""
        return MapPalette.style(key)

    @classmethod
    def _badge(cls, status: str, substitution: bool = False) -> str:
        """Return one status badge."""
        key = MapPalette.key_for(status, substitution)
        return f'<span class="s" style="{MapPalette.style(key)}">{html.escape(key)}</span>'

    @classmethod
    def _measures(cls, measures: Sequence[Mapping[str, Any]]) -> str:
        """Return the measure table: one row per catalogue measure with its options."""
        rows: List[str] = [
            "<h2>Measures</h2><table><tr><th>measure</th><th>status</th><th>options</th>"
            "<th>HiSim targets</th><th>note</th></tr>"
        ]
        for measure in measures:
            options = "".join(
                f"<li><code>{html.escape(str(option['name']))}</code> "
                f"{cls._badge(str(option['status']))}"
                f"{cls._values(option.get('values'))}</li>"
                for option in measure["options"]
            )
            targets = "".join(
                f"<li><code>{html.escape(str(target))}</code></li>"
                for target in measure["hisim_targets"]
            )
            rows.append(
                f"<tr><td><code>{html.escape(str(measure['measure_id']))}</code></td>"
                f"<td>{cls._badge(str(measure['status']), bool(measure.get('substitution')))}</td>"
                f"<td>{('<ul>' + options + '</ul>') if options else '&middot;'}</td>"
                f"<td>{('<ul>' + targets + '</ul>') if targets else '&middot;'}</td>"
                f"<td>{html.escape(str(measure.get('note') or ''))}</td></tr>"
            )
        rows.append("</table>")
        return "".join(rows)

    @classmethod
    def _values(cls, values: Optional[Sequence[Mapping[str, Any]]]) -> str:
        """Return the per-value badges of one option, when it has a value list."""
        if not values:
            return ""
        marked = [value for value in values if str(value["status"]) != "used"]
        if not marked:
            return ""
        rendered = " ".join(
            f"<code>{html.escape(str(value['value']))}</code>"
            f"{cls._badge(str(value['status']), 'modelled as' in str(value.get('note') or '').lower())}"
            for value in marked
        )
        return f"<ul><li>{rendered}</li></ul>"

    @classmethod
    def _fields(cls, fields: Sequence[Mapping[str, Any]]) -> str:
        """Return the inventory table: one row per request path the probes reached."""
        rows: List[str] = [
            "<h2>Inventory fields</h2><table><tr><th>request path</th><th>status</th>"
            "<th>values</th><th>note</th></tr>"
        ]
        for entry in fields:
            rows.append(
                f"<tr><td><code>{html.escape(str(entry['path']))}</code></td>"
                f"<td>{cls._badge(str(entry['status']), bool(entry.get('substitution')))}</td>"
                f"<td>{cls._values(entry.get('values')) or '&middot;'}</td>"
                f"<td>{html.escape(str(entry.get('note') or ''))}</td></tr>"
            )
        rows.append("</table>")
        return "".join(rows)

    @classmethod
    def _results(cls, results: Mapping[str, Sequence[Mapping[str, Any]]]) -> str:
        """Return the result pane: every field ``result.json`` can carry and what it will be.

        The two halves of the payload, one table each, straight out of the capability document's
        own ``results`` section -- which is generated from the tables the payload is built from,
        so the page cannot promise a field the payload does not carry.
        """
        parts: List[str] = [
            "<h2>Result payload</h2>",
            '<p class="meta">What one finished calculation answers with: every field of '
            "<code>result.json</code>, the source its number is read from, and what the number "
            "will be. A field with provenance <code>absent</code> is not published at all and "
            "says why.</p>",
        ]
        for block in (ResultsPane.KPIS_KEY, ResultsPane.COSTS_KEY):
            parts.append(f"<h3>{html.escape(block)}</h3>")
            parts.append(
                "<table><tr><th>field</th><th>provenance</th><th>source</th>"
                "<th>conditions</th></tr>"
            )
            for entry in results.get(block, ()):
                parts.append(
                    f"<tr><td><code>{html.escape(str(entry['field']))}</code></td>"
                    f"<td>{cls._provenance(str(entry['provenance']))}</td>"
                    f"<td>{html.escape(str(entry.get('source') or '')) or '&middot;'}</td>"
                    f"<td>{ResultsPane.conditions(entry)}</td></tr>"
                )
            parts.append("</table>")
        return "".join(parts)

    @classmethod
    def _provenance(cls, provenance: str) -> str:
        """Return one provenance badge, coloured like the status it corresponds to."""
        key = ResultsPane.PALETTE_KEYS.get(provenance, "approximated")
        return f'<span class="s" style="{MapPalette.style(key)}">{html.escape(provenance)}</span>'

    @classmethod
    def _trace(cls, trace: TraceExample) -> str:
        """Return the worked example: the request, the renovated house, the file and the report."""
        blocks = [
            ("The request (the vendored mockup)", json.dumps(trace.request, indent=2, ensure_ascii=False)),
            ("The house after the package", json.dumps(trace.renovated, indent=2, ensure_ascii=False)),
            (f"The energy-system file, from {trace.base_file}", trace.yaml_text),
            ("The mapping report", json.dumps(trace.report, indent=2, ensure_ascii=False)),
        ]
        parts = ["<h2>Worked example</h2>"]
        for title, body in blocks:
            parts.append(f"<h3>{html.escape(title)}</h3><pre>{html.escape(body)}</pre>")
        return "".join(parts)


def render(base_files_directory: Optional[Path] = None) -> str:
    """Return the translation map, in one call."""
    return TranslationMap.render(base_files_directory)
