# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest utsp

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: Test with pytest
      env:
        UTSP_URL: ${{ secrets.UTSP_URL }}
        UTSP_API_KEY: ${{ secrets.UTSP_API_KEY }}
      working-directory: ./tests/
      run: |
        pytest -m "utsp" --durations=0

    #    # stop the build if there are Python syntax errors or undefined names
       
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
