name: test-secrets
jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - shell: bash
        env:
          UTSP_URL: ${{ secrets.UTSP_URL }}
        run: |
          echo "$UTSP_URL"