name: test-secrets
on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - shell: bash
        env:
          UTSP_URL: ${{ secrets.UTSP_URL }}
        run: |
          echo "$UTSP_URL"